# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fuse-Class
version:      0.01
version_from: lib/Fuse/Class.pm
installdirs:  site
requires:
    Fuse:                          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
