--- #YAML:1.0
name:               Fuse-Class
version:            0.02
abstract:           Base clsas for Fuse module implementation using class.
author:
    - Toshimitsu FUJIWARA <tttfjw@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Fuse:        0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
